<a href="<?php echo App::config("url") ?>sudionik/add" class="success button expanded">
    Dodaj novog sudionika
</a>    
<div class="grid-x">
    <?php foreach($sudionici as $p): ?>
    <div class="cell large-3">
        <div class="success callout operateri">
            <?php
            ?>
            <h1><?php echo $p->ime?>
            <br />
            <?php echo $p->prezime?>
            </h1>
            <?php echo $p->email?>
            <hr />
            <a href="<?php echo App::config("url") ?>sudionik/prepareedit/<?php echo $p->sifra ?>">
                <i class="fas fa-edit fa-2x"></i>
            </a>

            <?php if($p->brojgrupa==0): ?>
                <a style="color: red;"
                    href="<?php echo App::config("url") ?>sudionik/delete/<?php echo $p->sifra ?>">
                    <i class="fas fa-trash fa-2x"></i>
                </a>
            <?php endif; ?>
        </div>
    </div>

    <?php endforeach; ?>
</div>
<nav aria-label="Pagination">
  <ul class="pagination text-center">
    <li class="pagination-previous"><a href="<?php echo App::config("url") ?>sudionik/index/<?php echo $prethodna ?>" aria-label="Next page">Prethodna <span class="show-for-sr">page</span></a></li>
    <li class="pagination-next"><a href="<?php echo App::config("url") ?>sudionik/index/<?php echo $sljedeca ?>" aria-label="Next page">Sljedeća <span class="show-for-sr">page</span></a></li>
  </ul>
</nav>
