<section class="contact-us-section">
  <div class="row medium-unstack">
    <div class="columns contact-us-section-left">
      <h1 class="contact-us-header"></h1>
      <div class="responsive-embed">
        <img src="https://www.google.com/maps/place/Ul.+Hrvatske+Republike+11,+31000,+Osijek/@45.5580625,18.6780953,17z/data=!3m1!4b1!4m5!3m4!1s0x475ce7a8acf9bed3:0xed862610eb16439!8m2!3d45.5580588!4d18.680284" alt="" alt="" />
      </div>

      <ul class="contact-us-list">
        <li class="address">Hrvatske Republike 11 31000 Osijek</li>
        <li class="email"><a href="mailto:">mkhrvatskisokol@gmail.com</a></li>
        <li class="phone">+385917965366</li>
      </ul>
    </div>
    <div class="columns contact-us-section-right">
      <h1 class="contact-us-header">Kontaktirajte nas</h1>
      <form class="contact-us-form">
        <input type="text" placeholder="Full name">
        <input type="email" placeholder="Email">
        <textarea name="message" id="" rows="12" placeholder="Type your message here"></textarea>
        <div class="contact-us-form-actions">
          <input type="submit" class="button" value="Pošalji" />
          <div>
            <label for="FileUpload" class="button contact-us-file-button">Priloži dokument</label>
            <input type="file" id="FileUpload" class="show-for-sr">
          </div>
        </div>
     </form>
    </div>
  </div>
</section>

